traceapp/tmpl/trace.html
With this change we based the timeline' width on the container' width
which allows it to adapt to various different screen sizes (as bootstrap
keeps the container size consistent using @media tags).
For the margin, we convert em units to pixels using the body's font-size.
Before & after screenshots on my small (~13inch) laptop screen:
Before: ![before](https://cloud.githubusercontent.com/assets/3173176/5867450/ac8b9618-a259-11e4-8b38-d13f6a9d1877.png)
After:
=> traceapp: add support for smaller screen sizes.

doc.go
This adds basic high-level package documentation to the `apptrace` package.
For details run `godoc`.
=> Add high-level package documentation.

collector_test.go, recorder_test.go
While looking through the tests I noticed a rather non-idiomatic `mockCollector` type used throughout the tests:
```
type mockCollector struct {
Collect_ func(SpanID, ...Annotation) error
}
func (c mockCollector) Collect(id SpanID, as ...Annotation) error {
return c.Collect_(id, as...)
}
```
Replace it with a more idiomatic pattern employed by `net/http.HandlerFunc`:
```
// collectorFunc implements the Collector interface by calling the function.
type collectorFunc func(SpanID, ...Annotation) error
// Collect implements the Collector interface by calling the function itself.
func (c collectorFunc) Collect(id SpanID, as ...Annotation) error {
return c(id, as...)
}
```
=> Replace mockCollector with collectorFunc.

traceapp/tmpl/root.html
I noticed that `apptrace` doesn't have a basic home-page that directs users to the `traces` tab.
At this point, I'm not entirely certain whether or not this was intentional or not. If it intentionally doesn't have one (maybe for embedding traceapp into other applications?) I still think we should have one for `cmd/apptrace`.
I've added a basic one with this PR that I think will suit most immediate purposes:
=> traceapp: add a basic home page.

httptrace/doc.go
This adds some extensive high-level usage documentation to the `httptrace` package for both Negroni and just-`net/http` based applications.
An actual example (a port of `cmd/apptrace/example_app.go` to use Negroni and `gorilla/context`) of Negroni-based usage will be added in the future.
=> httptrace: add Negroni and net/http usage documentation.

sqltrace/sql.go
This just adds some trivial documentation that is currently missing from the package.
Usage examples will come at a later time.
=> sqltrace: add basic package documentation

collector.go, recorder.go, store.go
Add some missing function' documentation, which was identified as missing by `golint`:
```
$ golint .
collector.go:192:1: exported method RemoteCollector.Collect should have comment or be unexported
recorder.go:54:1: exported method Recorder.Event should have comment or be unexported
store.go:61:1: exported method MemoryStore.Collect should have comment or be unexported
store.go:192:1: exported method MemoryStore.Trace should have comment or be unexported
store.go:207:1: exported method MemoryStore.Traces should have comment or be unexported
store.go:222:1: exported method MemoryStore.Delete should have comment or be unexported
```
=> Add some missing function documentation.

traceapp/tmpl/trace.html
Before this change, clicking or hovering over a timespan's label will
not work. If the text width is almost equal to the timespan's rectangle
width, or if the rectangle width is very small, it is very difficult to
click or hover over it (as the text blocks events from going to the
rectangle).
With this change, it is possible to hover over (to update the timeline
selector, or "hoverRes" div, in the bottom-left corner of the timeline)
and it is also possible to click on text label of a timespan to view
it's sub-spans.
From what I have found, d3-timeline does not itself support click or
hover events on timespan labels. To solve this, I've employed a workaround
using JQuery by selecting the next element and parsing the ID of it (which
has a data index suffix, i.e. the information associated …
=> traceapp: add support for clicking and hovering on timespan labels

traceapp/tmpl/trace.html, traceapp/vis.go
This can be merged after #5 is merged (or I'll re-base and resend).
This change helps #6 by properly display (and not crash JS) when displaying traces that do not contain TimespanEvent's in them (as currently generated by `--sample-data`). See the commit (of same name) for more details.
Before we had:
Due to:
After this change:
=> traceapp: Fix display of traces that contain no TimespanEvent's

traceapp/tmpl/trace.html
This change primarily pads the text displayed to the right of the hover resolver.
Additionally, it also replaces the CSS line:
```
.coloredDiv {
```
With a more correct (unaffecting outside `#hoverRes`) line:
```
#hoverRes .coloredDiv {
```
Before (note circled area):
After:
=> traceapp: pad the text displayed on the hover resolver

traceapp/tmpl/root.html, traceapp/tmpl/trace.html, traceapp/vis.go
Add support for a context menu that can show and hide specific spans.
By default, only the immediate children of the trace are visible, for example:
***
***
Instead of:
***
***
You can then right click (context menu button) on any timespan rectangle (e.g. `Request`) to bring up the context menu:
***
***
Clicking `Show Children` or `Hide Children` causes _all immediate and distant children of that span to be hidden/shown_. For example clicking `Show Children` on the `Request` span:
***
***
And then `Hide Children` on `Moonuiburg`:
***
=> Add support for a context menu that can show and hide specific spans.

cmd/apptrace/sample_data.go
This change has `--sample-data` generate fake SQL queries and tag information, it will help demonstrate the searching abilities I plan on adding soon.
Before:
***
After:
***
=> cmd/apptrace: Have --sample-data generate fake SQL and tag info.

traceapp/tmpl/layout.html, traceapp/tmpl/trace.html
This change adds a `Filter` option to the span right-click context menu:
***
Clicking the option brings up a sub-menu:
***
As mentioned in the tooltips added by this change (no screenshot), the `Filter` input box accepts a strict-search `key:value` pair. For example searching for `Name:"Shuplin"` on the top-level `Request` span:
***
Filtering shows or hides all children spans below the one you opened the context menu on. The strict searching pattern of `key:value` (where value is a `"quoted"` string) is used to allow for differentiation between strict and fuzzy searching in the future.
As another example, searching for `SQL:"SELECT * FROM table_name;"` (which is present in _all the fake timespan events_ generated by `--sample-data`) shows all the spans:
***
- Tooltips which detail each …
=> traceapp: add strict span filtering support.

traceapp/tmpl/layout.html, traceapp/tmpl/trace.html
This change makes use of fuzzy-searching on spans when the user uses an invalid strict filtering syntax (i.e. a key, colon, a quoted value -- `key:"value"`).
Searching a dataset like so (via right-click -> `Filter`):
***
For just `fr` produces:
***
Fuzzy searching is currently only performed on the `rawData.Name` and `rawData.Tag` fields -- I'll still have to extend this code a bit further to have it operate on all data fields in order to produce better results.
***
@sqs: To implement fuzzy-searching I made use of [fuse](http://kiro.me/projects/fuse.html) which is 1.58kb , and [Apache v2 licensed](https://github.com/krisk/Fuse/blob/master/LICENSE) -- is that okay?
=> traceapp: implement a fuzzy span filtering (a fallback to strict filtering)

traceapp/tmpl/trace.html
With this change, you can now fully strict or fuzzy search against all of
the keys in the spans. A fuzzy search for e.g. "200" would turn up results
properly now.
Also, we implicitly limit the filter/search string to 32 characters when
fuzzy searching as Fuse is limited to that, and will raise an exception
otherwise.
The tactic used for searching against all keys, is on a per-object (i.e.
per-span) basis. This means there is one fuse search per span object. I
also tried a single fuse search, but against the uniform (i.e. common) set
of keys shared by all the objects, but not all spans share the same set of
keys (and Fuse wants a strict set of keys to search against, specifically).
A more proper long-term fix for both of these would be to: modify Fuse to
search all object keys (when none …
=> traceapp: perform fuzzy search on all rawData keys.

traceapp/tmpl/layout.html
This has the browser use the appropriate schema whether on HTTPS or HTTP, and is generally better in all cases (e.g. connecting via a proxy or some other weird network which blocks HTTP(S) connections).
Primarily I employed this change because it is strange to use an inconsistent pattern in multiple places, and it seems like `//` is generally accepted over a specific one (or instead of mixing and matching).
=> traceapp: use schema-less ("//" vs "https://") includes for JS/CSS

traceapp/app.go, traceapp/prof.go, traceapp/router.go, traceapp/tmpl/layout.html, traceapp/tmpl/trace.html
This change adds the ability to switch between the current meta-data table view (which is the default):
***
***
To a new profiling view with the ability to show you which requests took the most (self time, self+children time, or cumulative time):
***
***
Clicking any of the table headers, for example `Time + Children (ms)`, sorts by that colum as you'd expect:
***
***
If you click on a span in the timeline UI to narrow your view onto the sub-span, you can like-wise also view profiling information for just that sub-span:
***
***
bootstrap-table.js (MIT licensed) is used to fetch and display the JSON profile data calculated on the Go web-server.
Additionally, two new public functions are exposed on `*traceapp.App`: `URLToTraceProfile` and `URLToTraceSpanProfile` which allow for the creation …
=> Add the ability to switch to a profiling view.

traceapp/tmpl/trace.html
By replacing the dots (.) in keys with underscores (_) when fuzzy searching each object, we communicate to Fuse that we really intend to search by that key, not by a sub-data object. As a comparison of what Fuse effectively tries to do:
- Before
- Object Key: `Response.StatusCode`
- Fuse: `obj.Response.StatusCode` (silently fails).
- After
- Object Key: `Response_StatusCode`
- Fuse: `obj.Response_StatusCode`
Fixes #24
=> traceapp: fix fuzzy search issue when keys contain periods

traceapp/vis.go
Checking depth == 0 is not the correct check to perform when acting
on sub-traces. A better check is to see if there is a parent span
or not. By doing this we do not generate two separate times (and
inherently, labels), which otherwise makes them very hard to read.
Fixes #26
(see issue for before photo) after:
=> traceapp: Do not generate multiple timespan events for sub-traces.

traceapp/prof.go, traceapp/tmpl/trace.html
This change enables clicking on table rows under profile-view. Clicking any row brings you to the span/sub-span page for that trace, as it would if you clicked it in the timeline. This allows one to find both the span ID as well as identify what span it is when e.g. names are the same or otherwise non-helpful.
Fixes #25
=> traceapp: enable clicking on profile-view table rows (go to span page).

traceapp/prof.go
This change makes the profiling times be calculated as floating-point numbers and rounded up, as they are in the d3 timeline. This is both more accurate and less confusing to users overall.
With this change we also appropriately grab the largest of the timespan events, rather than just the first one. This matches how apptrace already sends the timespans to the template for rendering in the timeline.
Before (see incorrect profile vs timeline times):
***
***
After (see identical profile & timeline times):
***
***
=> traceapp: generate profile times that exactly match the timeline.

demo-annotations.md, other-languages.md
This change adds two new Markdown files serving as general documentation of Appdash from other languages. These are lower-level details of how Appdash functions under the hood that I personally found useful during development of the `python/appdash` support library (see #36).
Helps #31
=> Document usage from other languages

event.go, httptrace/client.go, httptrace/server.go, span.go, sqltrace/sql.go, traceapp/tmpl/trace.html, traceapp/tmpl/traces.html
This change allows events to optionally implement the `ImportantEvent` interface. It enables events to return a list of annotation keys (e.g. `Response.StatusCode`) which thye find particularly important. Annotation keys not marked as important _are considered to be verbose_.
The UI is updated to reflect this change -- by splitting the data view tab into two separate tabs _Data View_ (only displays important span annotations) and _Verbose Data View_ (displays all span annotations).
Consider the _Data View_ before:
***
***
It now renders as just:
***
***
And the new _Verbose Data View_:
***
***
Additionally the _Traces_ page before:
***
***
Has been updated to only display _important_ annotations (which makes navigating lots of traces far easier):
***
***
For a more extravagant example …
=> Add optional ImportantEvent interface.

cmd/appdash/appdash.go, event.go, store.go, traceapp/app.go
This change adds the last of the documentation that I wanted to target / felt was missing. Primarily this is high-level package and command docs, plus a few targeted ones (like the fact that `appdash.MemoryStore` implements the `appdash.PersistentStore` interface).
All other public symbols are documented properly (from my own extensive review, and according to `go vet` / `golint`).
=> Add more documentation

collector_test.go, event_test.go, span_test.go, store_test.go
This change adds a bunch of benchmarks to the various `appdash` data types. Currently on my machine this reports:
```
BenchmarkChunkedCollector500    	    1000	   2447726 ns/op
BenchmarkMarshalEvent           	  100000	     16036 ns/op
BenchmarkUnmarshalEvents        	   50000	     35877 ns/op
BenchmarkIDGeneration           	10000000	       166 ns/op
BenchmarkFlatten                	  200000	      7431 ns/op
BenchmarkNewRootSpanID          	 5000000	       340 ns/op
BenchmarkNewSpanID              	10000000	       176 ns/op
BenchmarkSpanIDString           	  200000	      6694 ns/op
BenchmarkParseSpanID            	 2000000	       702 ns/op
BenchmarkMemoryStore100         	    3000	    555790 ns/op
BenchmarkMemoryStore250         	    2000	   1517543 ns/op
BenchmarkMemoryStore1000 …
```
=> Add a lot of benchmarks

traceapp/app.go, traceapp/router.go, traceapp/tmpl/layout.html, traceapp/tmpl/trace.html, traceapp/tmpl/traces.html, traceapp/trace.go
This change adds the ability to import and export single traces. A trace captured on one Appdash instance can be shared with other people as standard JSON-encoded text and imported directly into another retaining all information about the trace (spans, annotations, etc).
When viewing a specific trace there is now a _"Copy as JSON"_ link to the right of the trace ID, for example:
***
At which point the JSON-encoded trace will be copied to your clipboard:
***
On the Traces overview page (`/traces`) there is a new _"Import JSON"_ button:
***
Clicking the button slides out a textarea where you can paste a previously-exported JSON trace:
Attempts to upload traces that are duplicates or would collide (i.e. merge with an existing trace) are met with an error alert.
After importing a JSON trace, …
=> Add the ability to import and export single traces

traceapp/tmpl/root.html, traceapp/tmpl/trace.html
Prior to this change there was a mixed use of:
- Two-space indention (used all the time after this change is merged):
```
<html>
<div>
<strong>foo!</strong>
</div>
</html>
```
- Two-space indention with a leading one space indention (hard to work with in most editors):
```
<html>
<div>
<strong>foo!</strong>
</div>
</html>
```
- Tabs for indention.
I chose to go with 2-space indention due to that being used most prominently in the code base already. The usage of tabs (code I wrote) was accidental.
After this change we use just two-space indention for all HTML/CSS/JS code.
=> traceapp: use a standard 2-space indention in HTML template files.

traceapp/tmpl/root.html, traceapp/tmpl/trace.html, traceapp/tmpl/traces.html
Variables declared in JS through a simple:
```
var x = 0;
```
Are said to live in the global namespace. They can conflict with one another at any point. We use a few separate `<script>` tags for documentation and code separation purposes -- so it's hard to ensure that they do not declare conflicting variables and interfere with one another.
Instead, we now use an anonymous closure whose variables etc are local to that function's scope. For example:
```
(function() {
var x = 0;
})();
```
The diff is probably not very readable due to the old code being out-dented by two additional spaces now. But the above should make the intent of this change clear.
Can be merged after Travis is done checking #49 (or I'll re-base and send again if further changes are needed).
=> Clean global js namespace

traceapp/app.go, traceapp/tmpl/trace.html, traceapp/tmpl/traces.html
Prior to this change you could export and import a _single_ trace as JSON text at a time. After this change you can select multiple traces on the _Traces_ page and perform certain operations on them through the _Traces_ options drop-down menu:
***
***
By default all of the traces are selected. The _Traces_ drop-down menu features options to operate on traces:
***
***
Just as when copying a individual trace on it's page (via the `Copy as JSON` link) -- the `Export Selected` button copies the JSON trace data to your clipboard, which can then be imported using the `Import JSON` button on the _Traces_ page.
To simplify the process, the JSON format is now changed to an array of JSON `appdash.Trace` objects (even if there is only one trace being exported).
In the future, this menu will also …
=> traceapp: add support for exporting and importing multiple JSON traces.

httptrace/client.go, httptrace/server.go, traceapp/app.go, traceapp/tmpl/trace.html, traceapp/tmpl/traces.html
This change prefixes the fields (using the `trace` struct tag) of `httptrace.ServerEvent` and `httptrace.ClientEvent`.
For details about why this change is important, please see the linked issue. But in short:
Before:
***
***
After:
***
***
Fixes issue #45.
Note: waiting on Travis build of #51 (hence included change).
=> Prefix httptrace keys with Server/Client for clarity

httptrace/client.go, httptrace/server.go, traceapp/app.go, traceapp/trace.go
This change sorts the traces displayed on the _Traces_ page so that reloading the page multiple times does not shift them randomly.
Fixes issue #47.
Can be merged after the Travis build for #52 runs.
=> Sorted traces

traceapp/app.go, traceapp/router.go, traceapp/tmpl/data.go, traceapp/tmpl/layout.html, traceapp/tmpl/root.html, traceapp/tmpl/trace.html
This change switches to a nicer UI design overall for the `traceapp` package.
The static image files are built into the final single-binary using `go-bindata` and `go-bindata-assetfs` to serve them (also see the new [appdash-data](https://github.com/sourcegraph/appdash-data) repository).
Home page before:
---
---
Home page after:
---
---
Take note that the footer at the bottom of the page which says "Appdash is an open-source project created by Sourcegraph." starts out that way, and then changes every 10 seconds into a random helpful-hint about using Appdash.
Traces page before:
---
---
Traces page after:
---
---
Traceview before:
---
---
Traceview after:
---
---
=> traceapp: switch to a nicer UI design

traceapp/app.go, traceapp/tmpl/layout.html
This change cleans up some incorrect error handling, and corrects two mismatched HTML tags. It also has the footer fade in initially when the page loads.
=> traceapp: a few minor changes / code cleanup

cmd/appdash/sample_data.go, traceapp/aggregate.go, traceapp/app.go, traceapp/router.go, traceapp/tmpl.go, traceapp/tmpl/aggregate.html, traceapp/tmpl/data.go, traceapp/tmpl/traces.html
This change adds an aggregated data view for viewing multiple traces aggregated together. The idea is that all traces with the same name are joined together, and their total time spent is shown in the sorted pie-chart (rendered via [d3pie](http://d3pie.org/)).
To open aggregate view simply go to the _Traces_ page and select the traces you'd like to view, click the _Traces_ drop-down and select _Aggregate View_:
---
---
Selecting just five traces produces a page showing the cumulative time of just those five traces, showing that the traces named `zri.ozruamwe.ll` took the most time (25% of all selected traces):
---
---
Of course, using it on _all 60 traces_ produces a much more interesting result:
---
---
Showing that `fia.com` took 14% of the total time, followed by `web.kraesey.net` at …
=> traceapp: add Aggregate View

traceapp/tmpl/aggregate.html, traceapp/tmpl/layout.html
This change has all external JS libs that are not currently backed via a CDN (e.g. ones hosted via rawgit.com) served via the [appdash-data](https://github.com/sourcegraph/appdash-data) repository.
This ensures that:
- Appdash loads faster (I've personally seen rawgit.com slow to a halt a few times).
- The web UI does not break when no versions of these libraries are released.
=> traceapp: load external assets not backed by a CDN from appdash-data

cmd/appdash/sample_data.go, traceapp/aggregate.go, traceapp/app.go, traceapp/tmpl/aggregate.html
This change adds three different viewing modes to the new _Aggregate View_:
- _Root Spans_ - aggregate traces showing root-span names only.
- _Sub Spans_  - aggregate traces showing sub-span names only.
- _All Spans_ - aggregate traces showing all trace span names.
The httptrace package by default names root spans based on the request's
host field (i.e. the host server). This means that Root Spans will show
you the hosts taking up the most time in your system:
---
---
Sub-spans are typically sub-operations in your system, for example SQL
queries or outbound server-side HTTP requests, so Sub Spans view will
show you which sub-operations in your system took the most time:
---
---
If you're interested in which sub-operations took the most time in each
of your hosts (root traces), then All …
=> traceapp: add three different viewing modes to Aggregate View.

store.go, store_test.go
Similar to RecentStore, but caps memory usage.
=> LimitStore (deletes oldest trace when capacity is reached)

aggregate.go, aggregate_test.go
- Add two regression tests for AggregateStore.
- Add a test to ensure we do keep the N-Slowest traces properly (prior to this change we do not).
- Fix several issues related to storing N-slowest traces properly, identified through the new tests.
=> Add tests for AggregateStore & Fix several bugs

aggregate.go, aggregate_test.go
This change enables the usage of LimitStore / RecentStore / etc functionality in tangent with AggregateStore. For example I want to keep the N-slowest traces and aggregated trace data (what AggregateStore provides) plus also keep the last 5 minutes of traces (regardless of whether or not they are the N-slowest).
Prior to this change it was not possible. You could send collections to both stores, but if a trace happended to be one of the ones in the last 5 minutes and also one of the N-slowest you would end up with duplicate data in the backing store (assuming they went to the same backing store).
Depends on merge of #72
Fixes #71
=> Enable using LimitStore/RecentStore functionality with AggregateStore

aggregate.go
See each commit message for details, overview:
- Add AggregateStore statistics for debugging memory leaks.
- Fix a minor comment typo.
- Properly send collections to AggregateStore.Keep as it promises to.
- Use a workaround to avoid leaking memory in AggregateStore.
=> AggregateStore bug fixes

store.go, store_test.go
This change adds a test (failing before and passing after this change) regarding a serious bug in `LimitStore` where it would treat each individual collection as the beginning of a new trace (i.e., evicting an "old" trace even though the "new" one is already inside the `LimitStore`!).
=> Fix LimitStore so multiple collections don't evict traces early.

aggregate.go, aggregate_test.go, collector.go, collector_test.go, event.go, multi.go, store.go, store_test.go, trace.go, traceapp/dashboard.go
- Make `ChunkedCollector` more efficient and allocate less memory.
- Significantly lessen memory consumption of apps making use of `AggregateStore`.
- Add several new benchmarks and a few tests.
=> Improve performance of AggregateStore and ChunkedCollector

collector.go, collector_danger_test.go, memstats.go
This change improves performance of `ChunkedCollector` slightly, but also highlights an important issue (which I strongly believe will improve in Go 1.5, hopefully I will have time to test with 1.5 soon to verify). For now see the workaround mentioned in [Solution](#Solution) section 2.
(also see relevant tests and data at [Appdash PR #80](https://github.com/sourcegraph/appdash/pull/80))
I believe that `ChunkedCollector` when placing items into it's underlying map (which holds onto them for < 500ms in our prod. apps, and just 10ms in our tests) is indirectly causing 20-41k tiny heap objects to be allocated (but the Go code is NOT leaking them) and that the Go runtime is poorly equipped in Go 1.4 to either: 
1. Reuse these small objects behind the map so that many allocations do not need …
=> Improve ChunkedCollector performance slightly

httptrace/client_test.go, httptrace/server_test.go
These tests were failing (but not reported by Travis due to the Makefile,
soon to be removed by sourcegraph/appdash#84) due to the fact that the keys
changed previously and are now prefixed with Server/Client for easy
differentiation in the web UI.
=> httptrace: fix the failing tests

traceapp/app.go
This change switches `traceapp` to use the `http.FileSystem` generated directly by `vfsgen`.
Reasons for switching to `vfsgen` include:
- Consistency across all Sourcegraph code bases.
- Other projects _need_ vfsgen for its additional functionality, and it's good to use the same tool for this task.
- Ability to easily enable gzipped compression efficiently in the future.
- No need for a follow-up `go fmt ./...` after regeneration.
- Usage of `http.FileSystem` directly matches the needs of this project (bonus of being done in one package instead of across two separately maintained packages).
Note: This change should be merged at the same time as sourcegraph/appdash-data#5, because they depend on each other.
=> traceapp: Use http.FileSystem generated by vfsgen.

httptrace/client.go, httptrace/server.go, traceapp/tmpl/data/trace.html, traceapp/vis.go
- Default to using hostname _plus_ URL path, since this reflect what most users will want in the general case (note they can always set their own name, of course).
- Cut off really long span names (>14 characters) to avoid overlapping contents (limitation of d3-timeline).
- To show the full span name, just hover over it (a _very snappy_ tooltip will appear).
- Depends on https://github.com/sourcegraph/appdash-data/pull/7
Before:
----------------------------------------
----------------------------------------
After:
----------------------------------------
----------------------------------------
=> Improve ui

httptrace/server.go
This allows inner handlers to run and set information which the MiddlewareConfig
may want to use. A concrete example of this is having the middleware run before
mux has had a chance to set a route name.
This could potentially break existing uses if the inner handlers destroy or
mutate the information that MiddlewareConfig depended on.
=> httptrace: Collect Name & User after inner handler

.travis.yml, httptrace/client.go, httptrace/client_test.go
This PR enables `httptrace.Transport` to use timeout parameter and cancel request.
=> Added timeout feature for httptrace.Transport

traceapp/tmpl/data/trace.html, traceapp/vis.go
This PR improve trace view UI.
1. show full text on each timeline
2. show overflowed text on the edge of the right side data
3. left side has same feature as timeline data
- show tooltip when hovered
- show context menu when right click
=> Show overflow label on trace view

traceapp/tmpl/data/trace.html, traceapp/vis.go
This PR sort feature on trace view.
1. sort order by `starting_time`
2. sort order by `ending_time`
3. sort order by `latency` (added new filed)
4. sort order by `label` (alphabetically)
Each sort is worked as `ascending order` first click and `descending order` by clicking same button.
=> Added sort buttons on trace view

collector_test.go, testutil/testutil.go
Issue: #101 
- Improves `TestChunkedCollector` - it does intermittently fails becase `reflect.DeepEqual` cares about element position when comparing, so `expected` & `actual` variables being compare sometimes might have the same elements but in different order.
=> Improves TestChunkedCollector.

traceapp/app.go, traceapp/tmpl/data/trace.html, traceapp/vis.go
When visiting `/traces/:trace_id` d3 timeline chart is drawn which depends on `timelineItem.Label` and `timelineItem.FullLabel`, so when missing those values, frontend hangs forever.
- Which is set to false when `timelineItem.Label` or `timelineItem.FullLabel` are empty.
- When `showTimelineChart` is false, timeline chart is not drawn and we prevent the issue mentioned above.
/cc: @slimsag
=> Adds support to hide timeline chart on `/traces/:trace_id`

collector.go
So that we can track how often a Flush occurs.
/cc @neelance
=> add a ChunkedCollector.OnFLush callback for debugging purposes

collector.go
This enables us to debug what appears to be a queue buildup causing
Flush operations to take much longer and eventually leak memory.
=> add queueSize parameter to ChunkedCollector.OnFlush

traceapp/handler.go
Currently, the value of `rb.Status` is often `0` when an error happens. This is because in many error conditions, its value is never changed from its initial zero value when the error happens. This is an invalid HTTP status code that may be causing issues when serving via HTTP/2.
Always use 500 HTTP status code, which is is simpler and guaranteed to work in all situations. If desired to have more descriptive error messages, that can be an optional followup.
This may fix issues with responding to requests over HTTP/2.
Refactor `handleError` so it's no longer a closure.
=> traceapp: Always use 500 HTTP status code for errors.

collector.go, collector_test.go
This change adds a FlushTimeout field to ChunkedCollector which can be used to prevent a large queue from building up within the ChunkedCollector, effectively leaking/consuming large amounts of memory, due to an misbehaving underlying collector (like RemoteCollector, which would attempt to reconnect to a flaky remote server upon each collection).
/cc @neelance @keegancsmith
=> add a FlushTimeout field to ChunkedCollector to prevent memory consumption

traceapp/vis.go
Notes: 
- I've discovered this while working on #99:
- Based on `examples/cmd/webapp/main.go`:
- `MemoryStore` - won't save `_schema:HTTPClient` `Event` for root spans.
- When building d3 timeline data for a given root span - everything is fine, all other events different than (`_schema:HTTPClient`) are present & contains values.
- Based on `examples/cmd/webapp-influxdb/main.go`:
- `InfluxDBStore` - won't save `_schema:HTTPClient` `Event` for root spans.
- When building d3 timeline data for a given root span, event: `_schema:HTTPClient` & it's associated times are present & it's values are empty, not because we did saved but because `InfluxDB` will include in the query result all the `fields` from the `measurement` - and the field `_schema:HTTPClient` was created for other spans.
- We can …
=> Improvements on `D3 Timeline` data.

examples/cmd/webapp-influxdb/main.go
- Based on previous [conversation](https://github.com/chris-ramon/appdash/commit/ef7a19ab740b35d385c3ef2f42675b55572cded1#commitcomment-16596523) on PR #99.
=> updates to keep influxdb metrics reporting enabled

traceapp/app.go, traceapp/vis.go
- Follows up: https://github.com/sourcegraph/appdash/pull/108 which was already merged but #99 PR included a [commit](https://github.com/chris-ramon/appdash/commit/1ad279d67141b3c4cff25ff0986d804555f32317) that reverted it and includes feedback discussed [here](https://github.com/sourcegraph/appdash/pull/108#discussion_r52198747).
=> Adds emptiness time checking.

event.go, examples/cmd/webapp-opentracing/main.go, opentracing/recorder.go, opentracing/recorder_test.go, opentracing/tracer.go, recorder.go
This is the Appdash implementation of the OpenTracing api for Go. This is a really big diff, so I'd recommend ignoring the tests and the example app that's included for the time being. cc @slimsag
=> Adds the Appdash implementation of the OpenTracing API

influxdb_store_test.go
- Adds benchmarks for:
- Adds parallel benchmark for:
- `InfluxDBStore.Collect(...)`
```
$ go test -run=XYZ -bench BenchmarkInfluxDBStoreCollect. > collect
$ more collect
PASS
BenchmarkInfluxDBStoreCollect100-4           100        1103805936 ns/op
BenchmarkInfluxDBStoreCollect250-4           100        1364806193 ns/op
BenchmarkInfluxDBStoreCollect1000-4          100        1172157445 ns/op
ok      sourcegraph.com/sourcegraph/appdash     387.393s
```
- `InfluxDBStore.Trace(...)`
```
$ go test -run=XYZ -bench BenchmarkInfluxDBStoreTrace. -benchtime=40s > trace
$ more trace
PASS
BenchmarkInfluxDBStoreTrace100-4             200         411849069 ns/op
BenchmarkInfluxDBStoreTrace250-4              50        1051788921 ns/op
BenchmarkInfluxDBStoreTrace1000-4             10        4227713513 …
```
=> Adds InfluxDBStore benchmarks.

event_test.go, influxdb_store.go, influxdb_store_test.go
Issue: #117 
- Updates `func annotationsFromRow(...)` to include common logic that we use to reassemble data back from InfluxDB fields to span `annotations`. Now it uses `func annotationsFromEvents(..)` which will discard those annotations that should no be included because were not explicitly save by `Collect(...)` but that are present because `InfluxDB` will return all the fields present on `spans` measurement:
- Eg. A field named `Client.Request.Method` might contain values for sub-spans but not for root-spans. Since span annotations are non-deterministic, current strategy for query those annotations(fields) is to do `select * from spans ....`, therefore: `Client.Request.Method` will be included in the query result even for root-spans:
=> Improvements on reassembling back annotations from InfluxDB.

influxdb_store.go, influxdb_store_test.go
Issue: #118
Built on top of: #124
- Adds fallback for sub-traces which their parent was not found on trace root, so those sub-traces are added now to the trace root.
=> Improvements on `addChildren`.

aggregate_test.go, httptrace/client.go, httptrace/server.go, recorder.go, recorder_test.go
Related issue: https://github.com/sourcegraph/appdash/issues/132
- Adds `Recorder.Finish(...)` method, such that a span will only be recorded to once (a recorder produces only one `Store.Collect(...)` call for a given `SpanID`).
- Updates httptrace client & server to call `Recorder.Finish(...)` in order to collect the span.
- Fixes recorder tests.
=> Improvements on `Recorder`.

httptrace/client.go, httptrace/server.go, influxdb_store.go, influxdb_store_test.go
- Issue: #132 
- Not required anymore since the `httptrace` changed mentioned above; enables to have a single `InfluxDBStore.Collect(...)` call per `Recorder.Finish(..,)` call.
=> Perf. improvements for InfluxDBStore.

opentracing/recorder.go, opentracing/recorder_test.go
The opentracing recorder was recording all spans regardless of their sampling status.
=> opentracing: No longer record unsampled spans

CHANGELOG.md, recorder.go
This makes it such that, when a logger is set, you do not need to manually check the errors returned via the `Errors` method.
=> Add a Recorder.Logger field for logging errors instead of explicitly checking

CHANGELOG.md, examples/cmd/webapp-influxdb/main.go, influxdb_store.go, influxdb_store_test.go
Fixes #152 
Based on #154 for simplicity.
=> InfluxDBStore: cleanup InfluxDBStore configuration by adding sane defaults

CHANGELOG.md, influxdb_store.go
- Introduced by `094b22`
- `i` was renamed to `rowIndex` in that commit, but `results[i].Slowest = append(results[i].Slowest, id)`
was not updated to reflect this.
Confirmed fix by visiting the Dashboard page (no more panic).
Based on #155 for simplicity.
=> InfluxDBStore: fix index out of bounds panic on Dashboard

traceapp/tmpl/data/trace.html
Because {{.Permalink}} is already inclusive of the base URL that is given
as the base router parameter to `NewRouter`.
This fixes an issue with the trace permalinks where they were incorectly `//traces/<id>`
instead of `http://mysite.com/traces/<id>` for example.
Tested manually / locally.
=> traceapp/tmpl/data: do not use {{.BaseURL}}{{.Permalink}}

cmd/appdash/sample_data.go
If Finish isn't called, no data will ever be sent to the collector,
rendering 'appdash send' ineffective.
=> cmd/appdash: actually send spans to collector

CHANGELOG.md, cmd/appdash/example_app.go, cmd/appdash/serve_cmd.go, examples/cmd/webapp-influxdb/main.go, examples/cmd/webapp-opentracing/main.go, examples/cmd/webapp/main.go, traceapp/app.go, traceapp/tmpl.go
This change requires that users of traceapp pass a base URL parameter. This is
needed in order to create absolute URLs to e.g. traces for permalinks. Prior to
this change, we would get this base URL via `github.com/gorilla/mux.Route.URLTo`
but this notably enforces an HTTP-only scheme ([source code here](https://github.com/gorilla/mux/blob/master/route.go#L473))
which prevents Appdash permalinks from working on HTTPS hosted systems. This is
fixed with this change, by requiring an explicit base URL to be given as a
parameter.
Verified as working manually via the examples.
=> traceapp: take a base URL parameter in New

CHANGELOG.md, influxdb_store.go, vendor/github.com/influxdata/influxdb/client/v2/client.go, vendor/vendor.json
- Fix an index out of bounds panic when viewing the `/traces` page.
- Use a less memory intensive DB schema (users will need to `rm -rf ~/.influxdb` to remove the old DB).
- In our production application, this change shows a decrease from 40+ GB (and OOM panics) to ~2.4 GB of RAM usage.
- Upgrade to InfluxDB client v2 (fixes #140).
=> InfluxDBStore: various improvements (+lower memory usage)

python/appdash/__init__.py, python/appdash/event.py, python/appdash/recorder.py, python/example_opentracing_socket.py, python/setup.py
Now that https://github.com/opentracing/basictracer-python is a thing, I've added a python opentracing implementation for Python. What's really cool about this is that it's 100% compatible with the Golang implementation, so two processes can send each other spans and join traces using the inject/join methods.
I'm not too sure how python dependencies work(I'm not too great with python), but I changed setup.py to use setuptools to bring in the basictracer dependency.
=> Add OpenTracing Python implementation

examples/cmd/webapp-opentracing/main.go, opentracing/recorder.go
The concept of spancontexts were recently introduced with https://github.com/opentracing/opentracing.github.io/pull/100 and https://github.com/opentracing/basictracer-go/pull/29
Fixes #173 
cc @slimsag @shurcooL
=> opentracing: Update package to use span contexts

python/appdash/recorder.py
opentracing/basictracer-python removed Context.parent_id
https://github.com/opentracing/basictracer-python/commit/343ee8effc770afd1c69445bc8753107f48de51d
this patch gets the parent_id from basictracer's Span
=> Fixes compatibility with basictracer's SpanContext

README.md
External dependencies are not being managed using govendor or any
vendoring tool. The README is out of date and refers to previous
development workflow which included vendoring external dependencies.
Update the README to reflect the current state of the project and
remove references to govendor.
=> README: Remove reference to govendor

.travis.yml
Appdash can no longer be built using Go 1.6 with implicit external
dependencies. One or more upstream dependencies imports the "context"
package from the Go 1.7 standard library which means Appdash must use
Go 1.7 in order to build it. Using Go 1.6 causes the following build
error when using Travis CI:
package context: unrecognized import path "context"
Resolve the issue by updating the Travis CI build configuration to
use Go 1.7 as the minimum supported Go version.
=> travis: Go 1.7+ is the minimum supported version

python/example_opentracing_socket.py
Actual version of basictracer-python seems to had replaced
``parent`` by ``child_of``, as seen in:
https://github.com/opentracing/basictracer-python/blob/eaf86dc/basictracer/tracer.py#L50
=> FIX start_span(): basictracer-python was updated

examples/cmd/webapp-opentracing/main.go, examples/cmd/webapp/main.go
From negroni's Readme
**Notice**: This is the library formerly known as github.com/codegangsta/negroni -- Github will     
automatically redirect requests to this repository, but we recommend updating your references for clarity.
=> Change negroni repo link

id_test.go
I just randomly opened the id_test.go file and noticed that the variable naming in the first test made no sense 🤷‍♂️ .
=> fix variable naming in a test in id_test.go

README.md
The image linked to an S3 that was unowned and taken over by a researcher.
=> Remove image from README
